### ISSUE TITLE
Cannot make the examples work properly

### ISSUE THREAD

**Issue by wyxcoder** [dekimir/postgres-searchbox#15]
I used the docker version

![image](https://github.com/dekimir/postgres-searchbox/assets/47443766/7a67a256-139c-467d-88ac-773c981ac3bd)

![image](https://github.com/dekimir/postgres-searchbox/assets/47443766/a095bd17-9546-4ceb-bb64-8bd8f8bfcd7d)

**Comment by dekimir** [comment]
Sorry!  Fixed now. :)
